MyFramework.Web/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFramework.Business.Abstract;
using MyFramework.Entities.Concrete;
using MyFramework.Web.Filters;
using MyFramework.Web.Infrastructure;
using MyFramework.Web.Models.ViewModel;

namespace MyFramework.Web.Controllers
{
    [AuthorizationFilter]
    public class SupplierController : BaseController
    {
        private ISupplierService _supplierService;

        public SupplierController(ISupplierService supplierService)
        {
            _supplierService = supplierService;
        }

        public ActionResult Index()
        {
            SupplierListViewModel supplierList = new SupplierListViewModel
            {
                Suppliers = _supplierService.GetAll()
            };
            return View(supplierList);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            if (!ModelState.IsValid)
            {
                ErrorNotification("Kayıt Eklenemedi!");
                return View("Create");
            }
            _supplierService.Add(supplier);
            SuccessNotification("Kayıt Eklendi.");
            return RedirectToAction("Index");
        }


        public ActionResult Update(int id)
        {
            Supplier model = _supplierService.GetById(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Update(Supplier model)
        {
            _supplierService.Update(model);
            SuccessNotification("Kayıt Güncellendi.");
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
             _supplierService.Delete(id);
            SuccessNotification("Kayıt Silindi.");
            return RedirectToAction("Index");
        }
    }
}

MyFramework.Web/Views/Supplier/Create.cshtml
@model Supplier
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginCard("Product Create"))
{
    using (Html.BeginForm(Url.Action("Create", "Supplier")))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false, "", new { @class = "w3-text-red" })

        @HtmlComponents.TextInputComponent("CompanyName", "Şirket İsmi")
        @HtmlComponents.TextInputComponent("ContactName", "İletişim İsmi")
        @HtmlComponents.TextInputComponent("ContactTitle", "İletişim Başlığı")
        @HtmlComponents.TextInputComponent("Address", "Adres")
        @HtmlComponents.TextInputComponent("City", "Şehir")
        @HtmlComponents.TextInputComponent("Region", "Bölge")
        @HtmlComponents.TextInputComponent("PostalCode", "Posta Kodu")
        @HtmlComponents.TextInputComponent("Country", "Ülke")
        @HtmlComponents.TextInputComponent("Phone", "Telefon")
        @HtmlComponents.TextInputComponent("Fax", "Fax")
        @HtmlComponents.TextInputComponent("HomePage", "Ana Sayfa")
        @HtmlComponents.SubmitComponent("Ekle")
    }

}

MyFramework.Web/Views/Supplier/Index.cshtml
@model SupplierListViewModel
@{
    ViewBag.Title = "Satıcı Listesi";
}

@using (Html.BeginCard("Satıcı Listesi"))
{
    @HtmlComponents.NewAddButtonComponent(Url.Action("Create", "Supplier"))
    using (Html.BeginTable(new[] { "Satıcı İsmi", "Bağlantı İsmi", "Telefon", "" }))
    {
        foreach (var item in Model.Suppliers)
        {
            <tr>
                <th>@item.CompanyName</th>
                <th>@item.ContactName</th>
                <th>@item.Phone</th>
                <th>
                    @HtmlComponents.DetailButtonComponent(Url.Action("Update", new { id = item.SupplierId }))
                    @HtmlComponents.DeleteButtonComponent(Url.Action("Delete", new { id = item.SupplierId }))
                </th>
            </tr>
        }
    }
}

MyFramework.Web/Views/Supplier/Update.cshtml
@model Supplier
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginCard("Product Create"))
{
    using (Html.BeginForm(Url.Action("Update", "Supplier")))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false, "", new { @class = "w3-text-red" })

        @HtmlComponents.TextInputComponent("CompanyName", "Şirket İsmi",Model.CompanyName)
        @HtmlComponents.TextInputComponent("ContactName", "İletişim İsmi", Model.ContactName)
        @HtmlComponents.TextInputComponent("ContactTitle", "İletişim Başlığı", Model.ContactTitle)
        @HtmlComponents.TextInputComponent("Address", "Adres", Model.Address)
        @HtmlComponents.TextInputComponent("City", "Şehir", Model.City)
        @HtmlComponents.TextInputComponent("Region", "Bölge", Model.Region)
        @HtmlComponents.TextInputComponent("PostalCode", "Posta Kodu", Model.PostalCode)
        @HtmlComponents.TextInputComponent("Country", "Ülke", Model.Country)
        @HtmlComponents.TextInputComponent("Phone", "Telefon", Model.Phone)
        @HtmlComponents.TextInputComponent("Fax", "Fax", Model.Fax)
        @HtmlComponents.TextInputComponent("HomePage", "Ana Sayfa", Model.HomePage)
        @HtmlComponents.HiddenInputComponent("SupplierId", Model.SupplierId.ToString())
        @HtmlComponents.SubmitComponent("Güncelle")
    }

}