MyFramework.Web/Models/ViewModel/RootPlanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MyFramework.Entities.ComplexType;
using MyFramework.Entities.Concrete;

namespace MyFramework.Web.Models.ViewModel
{
    public class RootPlanViewModel
    {
        public List<RootPlanDetail> RootPlans { get; set; }
        public List<RootPoint> RootPoints { get; set; }
    }
}

MyFramework.Web/Controllers/RootPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MyFramework.Business.Abstract;
using MyFramework.Entities.Concrete;
using MyFramework.Web.Infrastructure;
using MyFramework.Web.Models.ViewModel;

namespace MyFramework.Web.Controllers
{
    public class RootPlanController : BaseController
    {
        private IRootPlanService _rootPlanService;
        private ISupplierService _supplierService;
        private IRootPointService _rootPointService;
        public RootPlanController(IRootPlanService rootPlanService, ISupplierService supplierService, IRootPointService rootPointService)
        {
            _rootPlanService = rootPlanService;
            _supplierService = supplierService;
            _rootPointService = rootPointService;
        }
        // GET: RootPlan
        public ActionResult Index()
        {

            RootPlanListViewModel model = new RootPlanListViewModel();
            model.RootPlans = _rootPlanService.GetListRootPlanDetails();
            model.Suppliers = _supplierService.GetAll();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(RootPlan model)
        {
            var rootCount = _rootPlanService.GetAll().Where(x => x.Time == model.Time && x.DayOfWeek == model.DayOfWeek && x.IsActive == true).ToList().Count;
            if (rootCount > 0)
            {
                TempData["RootPlanAlreadyExist"] = "EKlemek istediğiniz gün ve saatte plan bulunmaktadır";
            }

            _rootPlanService.Add(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _rootPlanService.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult GeziRehberi()
        {
            RootPlanViewModel model = new RootPlanViewModel();
            model.RootPlans = _rootPlanService.GetListRootPlanDetails().Where(x => x.DayOfWeek == DateTime.Now.DayOfWeek).OrderBy(x => x.Time).ToList();
            model.RootPoints = _rootPointService.GetRootPlan();
            return View(model);
        }
        [HttpPost]
        public JsonResult CheckPlan(int? Id)
        {
            _rootPointService.PlanCheck(Id.Value);
            string json = @"{
                          'status': 'success',
                          'durum': 'Başarılı',
                          'icerik':'Kontrol noktası check edildi'}";

            JavaScriptSerializer ser = new JavaScriptSerializer();
            var m = ser.DeserializeObject(json);
            return Json(m, JsonRequestBehavior.AllowGet);
        }
    }
}

MyFramework.Web/Views/RootPlan/GeziRehberi.cshtml
@model RootPlanViewModel
@{
    ViewBag.Title = "Gezi Rehberi";

}

@using (Html.BeginCard("Bugün Kİ Gezİ Rehberİ"))
{
    <ul class="todo-list-item ui-sortable" id="todo-list">
        @foreach (var item in Model.RootPlans)
        {
            bool check = Model.RootPoints.Select(x => x.RootPlanId).Contains(item.RootPlanId);

            <li class="clearfix @(check ? "todo-done" : "")">

                <div class="chk-todo-my pull-left">
                    <div class="icheckbox_minimal-green @(check ? "checked" : "")" style="position: relative;">
                        <input type="checkbox" style="position: absolute; opacity: 0;" onclick="rootCheck(@item.RootPlanId)">

                    </div>

                </div>
                <p class="todo-title hidden-md hidden-sm hidden-xs">
                    @item.SupplierName adlı kişiye planlama yapılmış
                </p>
                <div class="action-todo pull-right clearfix" style="margin-bottom: 10px">
                    <a href="#" class="todo-edit"><i class="icon-clock"></i><span style="border-radius: 10px;width: 60px; color: black;font-size: 17px">Saat @item.Time</span></a>
                    <a href="#">
                        <i class="fa fa-user"></i>
                        <span class="btn btn-danger btn-sm" style="border-radius: 10px;width: 120px;">@item.SupplierName</span>
                    </a>
                </div>
            </li>
        }


    </ul>
}




@section css{
    <style>
        .chk-todo-my {
            margin-right: 10px;
            position: relative;
            top: -2px;
        }

        .todo-done {
            background-color: #a288d2;
        }

        .action-todo a {
            height: 24px;
            width: 150px;
            display: inline-block;
            float: left;
        }
    </style>
}
@section js{

    <script>
        function rootCheck(id) {
            $.ajax({
                method: "POST",
                url: "/RootPlan/CheckPlan",
                data: { Id: id }
            }).done(function (result) {
                console.log(result);
                swal(result.durum, result.icerik, result.status).then((ok) => {
                    location.reload();
                });
                console.log(result);
            }).fail(function (result) {
                console.log(result);
            }).always(function () {

            });
        }
    </script>
}

MyFramework.Web/Views/RootPlan/Index.cshtml
@model RootPlanListViewModel
@{
    ViewBag.Title = "Root Planı";


    string[] times = { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30" };

    var list = new List<KeyValuePair<DayOfWeek, string>>();
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)1, "Pazartesi"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)2, "Salı"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)3, "Çarşamba"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)4, "Perşembe"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)5, "Cuma"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)6, "Cumartesi"));
    list.Add(new KeyValuePair<DayOfWeek, string>((DayOfWeek)0, "Pazar"));

}



<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary rootplan" style="margin-bottom: 15px; background-color: #5fc6e6;border-color: #5fc6e6; "><i class="fa fa-sign-out"></i> Yeni Plan Ekle</a>
        <a href="@Url.Action("GeziRehberi","RootPlan")" class="btn btn-success" style="margin-bottom: 15px; "><i class="fa fa-plane"></i> Günün Rehberi</a>

        <div class="agenda">
            <div class="table-responsive">
                <table class="table table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th>Saatler</th>
                            @foreach (var item in list)
                            {
                                <td>@item.Value</td>
                            }

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var time in times)
                        {

                            <tr>
                                <td class="agenda-date" class="active">
                                    <div class="dayofmonth">@time</div>
                                </td>

                                @foreach (var gunler in list)
                                {
                                    var entry = Model.RootPlans.Find(x => x.DayOfWeek == gunler.Key && x.Time == time);

                                    if (entry != null)
                                    {

                                        <td class="agenda-date" class="active">

                                            <div class="full">
                                                <div class="dayofmonth"><i class="fa fa-calendar"></i></div>
                                                <div class="dayofweek">@entry.SupplierName</div>

                                                <div class="dayofweek" style="margin-top:16px;"><a href="@Url.Action("Delete","RootPlan",new {id=entry.RootPlanId})"><i class="btn btn-default btn-xs fa fa-remove"></i></a></div>

                                            </div>

                                        </td>
                                    }
                                    else
                                    {
                                        <td class="agenda-date" class="active"></td>
                                    }
                                }




                            </tr>
                        }


                        <!-- Multiple events in a single day (note the rowspan) -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>



@section css{
    <!--calendar-->
    <link href="~/assets/js/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <style>

        .agenda .agenda-date {
            width: 170px;
        }

            .agenda .agenda-date .dayofmonth {
                width: 40px;
                font-size: 25px;
                line-height: 36px;
                float: left;
                text-align: right;
                margin-right: 10px;
            }

            .agenda .agenda-date .shortdate {
                font-size: 0.75em;
                color: white;
            }

        .agenda .agenda-time {
            width: 140px;
        }

        table {
            background-color: white
        }

            table thead tr {
                height: 30px;
                line-height: 30px;
                text-align: center;
                background: #f6f6f6 !important;
            }

                table thead tr th {
                    width: 170px;
                }

        .agenda-date {
            border-color: #ebebeb !important;
            color: #a3a3a3 !important;
            font-weight: normal;
        }

        .full {
            background-color: #5fc6e6;
            color: white;
        }

        table thead tr th:first-child {
            width: 70px !important;
        }

        table tbody tr td:first-child {
            width: 70px !important;
        }
    </style>
}
@section js{

    @*Modal Popap*@
    <div class="modal" id="PlanEkleModal">
        <div class="modal-dialog">
            <div class="panel">
                <div class="panel-heading">Plan Oluştur</div>
                @using (Html.BeginForm(Url.Action("Add", "RootPlan", FormMethod.Post)))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel-body">
                        <div class="form-horizontal form-bordered p-lg">

                            <div class="form-group">
                                <label class="col-md-3 control-label" for="modalAciklama">Saat Seçiniz</label>
                                <div class="col-md-6">
                                    <select style="width: 100%" class="form-control select2" name="Time" required="required">

                                        @foreach (var item in times)
                                        {
                                            <option value="@item">@item</option>
                                        }
                                    </select>

                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label" for="modalAciklama">Gün Seçiniz</label>
                                <div class="col-md-6">
                                    <select style="width: 100%" class="form-control select2" name="DayOfWeek" required="required">

                                        @foreach (var item in list)
                                        {
                                            <option value="@item.Key">@item.Value</option>
                                        }
                                    </select>

                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label" for="modalAciklama">Tedarikçi Seçiniz</label>
                                <div class="col-md-6">
                                    <select style="width: 100%" class="form-control select2" name="SupplierId" required="required">

                                        @foreach (var item in Model.Suppliers)
                                        {
                                            <option value="@item.SupplierId">@item.CompanyName</option>
                                        }
                                    </select>

                                </div>
                            </div>


                            <button type="submit" class="btn btn-success">Ekle</button>
                        </div>
                    </div>
                }
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
    @*Modal Popap*@



    @* Plan KontrolDeğeri*@
    <div id="tempdata">@TempData["RootPlanAlreadyExist"]</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            var deger = $("table>td:first").text();

            if (deger != "") {
                alert(deger);
            }

            var planexist = $("#tempdata").html();
            if (planexist != "") {
                swal("Plan Mevcut", planexist, "error");
            }
        });


        $(".rootplan").click(function () {

            $("#PlanEkleModal").modal("show");
        });

    </script>
}